baseURL = 'https://example.org/'
languageCode = 'zh-Hans'
title = 'DjangoZane'
paginate = 10

[menus]
  [[menus.main]]
    identifier = 'home'
    name = '首页'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    identifier = 'posts'
    name = '文章'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    identifier = 'tags'
    name = '标签'
    pageRef = '/tags'
    weight = 30

[params]
  [params.search]
    enabled = true
  [params.photoswipe]
    enabled = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    noClasses = false

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
