baseURL = 'https://example.org/'
locale = 'zh-Hans'
title = 'DjangoZane'
paginate = 10

[menus]
  [[menus.main]]
    identifier = 'home'
    name = '首页'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    identifier = 'posts'
    name = '文章'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    identifier = 'tags'
    name = '标签'
    pageRef = '/tags'
    weight = 30

[params]
  # 这里的静态资源都需要放在static目录下，
  # 比如下面的背景图就是在 static/bg.jpg
  # logo 是在 static/images/logo.png
  # logo = '/images/logo.png'
  # favicon = '/favicon.svg'
  # backgroundImage = 'bg.jpg'
  [params.search]
    enabled = true
  [params.photoswipe]
    enabled = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    noClasses = false

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
